server:
  port: 8010
spring:
  application:
    name: myfirst-server
  datasource:
    url: jdbc:sqlserver://10.1.80.150:1433;databaseName=AdventureWorks2019
    username: adventure
    password: AdventureWorks
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2008Dialect
